# Generated by Django 4.1.12 on 2023-10-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_content_order_module_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='image',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='video',
        ),
    ]
